# Site settings
author: Brian Barnes
title: Websoftware
header-img: img/home-bg.png
email: brianb@rueziffra.com
copyright_name: Brian Barnes
description: > # this means to ignore newlines until "baseurl:"
  Creating for the world through the Internet.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  web-software

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
